// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxL0MmkcW_gKlgomkZt-BPwqow5FYGhE',
    appId: '1:431999683453:web:c2efa71efa663ef51f1a14',
    messagingSenderId: '431999683453',
    projectId: 'learn3-c51e0',
    authDomain: 'learn3-c51e0.firebaseapp.com',
    storageBucket: 'learn3-c51e0.firebasestorage.app',
    measurementId: 'G-5RHNPPMEYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWyA6GGsJUMdWVz_jip3_SR9mpPF15C0',
    appId: '1:431999683453:android:37c787065325da391f1a14',
    messagingSenderId: '431999683453',
    projectId: 'learn3-c51e0',
    storageBucket: 'learn3-c51e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDGgazE9MjG6YfYLq-tnWk5vmwAcp-gmA',
    appId: '1:431999683453:ios:e2d0f8f1b242f7731f1a14',
    messagingSenderId: '431999683453',
    projectId: 'learn3-c51e0',
    storageBucket: 'learn3-c51e0.firebasestorage.app',
    iosBundleId: 'com.example.learen3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDGgazE9MjG6YfYLq-tnWk5vmwAcp-gmA',
    appId: '1:431999683453:ios:e2d0f8f1b242f7731f1a14',
    messagingSenderId: '431999683453',
    projectId: 'learn3-c51e0',
    storageBucket: 'learn3-c51e0.firebasestorage.app',
    iosBundleId: 'com.example.learen3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALxL0MmkcW_gKlgomkZt-BPwqow5FYGhE',
    appId: '1:431999683453:web:c991260097cbad611f1a14',
    messagingSenderId: '431999683453',
    projectId: 'learn3-c51e0',
    authDomain: 'learn3-c51e0.firebaseapp.com',
    storageBucket: 'learn3-c51e0.firebasestorage.app',
    measurementId: 'G-Y5CDQ1NJ60',
  );
}
